# Generated by Django 4.2.6 on 2023-10-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_student_current_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_time',
            field=models.ForeignKey(default='любое время', on_delete=django.db.models.deletion.SET_DEFAULT, to='automation.studyingtime', verbose_name='Время созвона'),
        ),
    ]
