# Generated by Django 4.2.6 on 2023-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_project_student_current_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='call_time',
            field=models.TimeField(null=True, verbose_name='время созвона'),
        ),
    ]
