# Generated by Django 4.2.6 on 2023-10-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_student_preferred_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='automation.project', verbose_name='проект'),
        ),
    ]
