# Generated by Django 4.2.6 on 2023-10-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_project_call_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='telegram ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='automation.project', verbose_name='текущий проект'),
        ),
    ]
