# Generated by Django 4.2.6 on 2023-10-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_student_telegram_id_alter_student_current_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_from_far_east',
        ),
    ]
