# Generated by Django 4.2.6 on 2023-10-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_studygroup_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='call_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.studyingtime'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.projectmanager', verbose_name='менеджер'),
        ),
    ]
