# Generated by Django 4.2.6 on 2023-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_alter_studygroup_call_time_alter_studygroup_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='call_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='день созвона'),
        ),
    ]
