# Generated by Django 4.2.6 on 2023-10-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_devmanuser_students_studyingtime_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('newbie', 'новичок'), ('newbie_plus', 'новичок+'), ('junior', 'джун')], default='newbie', max_length=12, verbose_name='уровень студента')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название команды')),
                ('call_day', models.DateTimeField(verbose_name='День созвона')),
                ('call_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.studyingtime')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='call_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pmanager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.RemoveField(
            model_name='team',
            name='student',
        ),
        migrations.RemoveField(
            model_name='devmanuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AlterField(
            model_name='devmanuser',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Pm',
            new_name='ProjectManager',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.projectmanager', verbose_name='менеджер'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='automation.project', verbose_name='проект'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='automation.studygroup', verbose_name='текущая группа'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_time',
            field=models.ForeignKey(default='любое время', on_delete=django.db.models.deletion.SET_DEFAULT, to='automation.studyingtime'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devman_user', to='automation.devmanuser'),
        ),
    ]
